### PR TITLE
make python cflags validator check for python2 and python3

### LINKED ISSUE #7: python was not found in the pkg-config search path
The build fails on ArchLinux :(
I get
```
Package python was not found in the pkg-config search path.
Perhaps you should add the directory containing `python.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python' found
```
It seems that `pkg-config` does not work for `python` but works for `python3` and `python2`.
```
$ pkg-config --cflags python 
Package python was not found in the pkg-config search path.
Perhaps you should add the directory containing `python.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python' found
$ pkg-config --cflags python3
-I/usr/include/python3.6m
$ pkg-config --cflags python2
-I/usr/include/python2.7
```
If I remove the validator for `python` then the build completes successfully.
Would it be appropriate to check for `python`, `python2` and `python3` in the validator and return `true` if at least one works ?

### PR DESCRIPTION
**Pull request by rdeits**
Fixes #7 (hopefully)

### CODE REVIEW

**Comment by rdeits** [comment]
cc @blegat

File: deps/build.jl [hunk 1]
```diff
@@ -3,20 +3,22 @@ using CMakeWrapper
...
-            return true
-        catch ErrorException
-            return false
+        for pkg_name in pkg_names
+            try
+                run(`pkg-config --cflags $(pkg_name)`)
+                return true
+            catch ErrorException
+            end
+            false
```
Comment (blegat) [inline deps/build.jl]: Shouldn't this `false` be outside the `for` loop ?

Comment (rdeits) [inline deps/build.jl]: good point, thanks
